### ISSUE TITLE
Написать 1 главу 

### ISSUE THREAD

**Issue by serykhelena** [lsd-maddrive/climate_chamber#5]
Написать 1 главу в соответствии с планом 

https://docs.google.com/document/d/1HxvQmF2TThBnpQAJ7qIhhZ3LbZ4wN9IdxRYtMGMEZmI/edit?usp=sharing 

Вот примеры ВКР из прошлых лет, может посмотреть как оно вообще выглядит 
- https://drive.google.com/file/d/1hoMqr6Pu4cLjfwzLoef9h7aiNVqf3jGD/view?usp=sharing 
- https://docs.google.com/document/d/1CF5haBFrtQ24Z1PwWzKJ7k_O391Z4XKzfhOl7LmafS4/edit?usp=sharing

**Comment by PanDanil777** [comment]
[ДИПЛОМ.docx](https://github.com/lsd-maddrive/climate_chamber/files/13425777/default.docx)
